name: gluon_vision_docs
dependencies:
- python
- sphinx>=1.5.5
- scipy
- matplotlib
- sphinx_rtd_theme
- pip:
  - sphinx-gallery
  #- sphinxcontrib-versioning
  - git+https://github.com/Lingnik/sphinxcontrib-versioning@Lingnik-patch-1
  - mxnet-cu80>=1.2.0b20180418
  # - guzzle_sphinx_theme
  - recommonmark
  - Image
  - awscli
