name: gluon_vision_docs
dependencies:
- python
- sphinx>=1.5.5
- scipy
- numpy
- matplotlib
- sphinx_rtd_theme
- pip:
  - https://github.com/mli/mx-theme/tarball/0.3.1
  - sphinx-gallery
  - https://repo.mxnet.io/dist/2019-12-08/dist/mxnet_cu92mkl-1.6.0b20191208-py2.py3-none-manylinux1_x86_64.whl
  # - guzzle_sphinx_theme
  - recommonmark
  - Image
  - awscli
  - tqdm
  - requests
  - Pillow
  - opencv-python
  - portalocker
  - decord
